### ISSUE TITLE
Game grinding to a halt after updating to Modpack Version 1.8

### ISSUE THREAD

**Issue by Nemu86** [ChosenArchitect/Project-Architect#154]
**Describe the bug**
-> After updating to Modpack Version 1.8 the world loads up normally, but after 5 minutes it starts to lag and stutter quite a bit. FPS and TPS spikes happen more and more frequent until after around 15 minutes the game just comes to an halt. 
Switching to peaceful mode might extend this time by around 3 or 4 minutes.

**To Reproduce**
1.  Play a world in 1.7
2.  Upgrade mod pack to 1.8
3.  Load up saved world
4.  FPS & TPS spikes will start to occur more frequently
5.  Game halts

**Expected behavior**
-> The game should run smoothly without FPS & TPS spikes after the update

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Modpack version**
-> 1.8
**Java Version**
-> 1.8.0.201 64 Bit
**Modpack Launcher Used**
-> CurseForge
**Ram Allocated**
-> 10 GB

**Additional context**
->

**Comment by Delfite** [comment]
This wreaks of a memory leak. Can you show some screenshots of a before and after of Minecraft's F3 Debug Screen and the "Performance" tab in Task Manager?

Screenshots can be taken using "Windows Key+Shift+S" (keyboards with the apple logo instead will still do the same thing)

**Comment by Nemu86** [comment]
Sure
Here's my game with Modpack 1.7
![Screenshot 2022-03-10 202353](https://user-images.githubusercontent.com/101342872/157739407-0ba06ace-4452-4dce-9416-9c3031407f1a.png)
Taskmanager with Modpack 1.7
![Screenshot 2022-03-10 202428](https://user-images.githubusercontent.com/101342872/157739545-7fd88026-3f78-4e96-8421-8a30dd66d969.png)

Modpack 1.8 at the start
![Screenshot 2022-03-10 203409](https://user-images.githubusercontent.com/101342872/157740889-8fb47685-978e-4994-a8fd-f7c7e6a8d3d6.png)
![Screenshot 2022-03-10 203429](https://user-images.githubusercontent.com/101342872/157740910-1ac777e6-0dbb-4e57-8885-c3951bce504c.png)

After a few minutes
![Screenshot 2022-03-10 204426](https://user-images.githubusercontent.com/101342872/157742616-12a757d3-8bc9-4a89-bbd8-8331ed4b4130.png)
![Screenshot 2022-03-10 204453](https://user-images.githubusercontent.com/101342872/157742635-a4827079-29a2-4b6f-ae30-4034cecde6fe.png)

First lag spike
![Screenshot 2022-03-10 204706](https://user-images.githubusercontent.com/101342872/157742935-7f7fe262-fba2-4ecb-a38c-ec46fc4e7c57.png)

Around 10mins later
![Screenshot 2022-03-10 205453](https://user-images.githubusercontent.com/101342872/157744190-315cc2bf-a3f4-40c6-8a6d-b05f1feb8c44.png)
![Screenshot 2022-03-10 205605](https://user-images.githubusercontent.com/101342872/157744384-affff053-89b8-4e7b-b9d9-b7ac4b999634.png)

Last screen before it died like 4 mins later
![Screenshot 2022-03-10 205716](https://user-images.githubusercontent.com/101342872/157744739-a1057ae9-6886-4b11-9978-3d45b7916dab.png)
![Screenshot 2022-03-10 205758](https://user-images.githubusercontent.com/101342872/157744756-99c93725-6e93-43cb-b7fe-2b4fa80a7eb8.png)

**Comment by James103** [comment]
Can you test this
1. in a fresh new world?
2. in a new void world (Superflat -> Customize -> Presets -> Select Void World)?

**Comment by Nemu86** [comment]
Sure in a fresh new world after 10 min nothing happend
![Screenshot 2022-03-11 001202](https://user-images.githubusercontent.com/101342872/157770791-a6124f0e-88cc-4aa8-bff0-497c7cddb5ce.png)

Superflat void world after 10 min nothing happend
![Screenshot 2022-03-11 002535](https://user-images.githubusercontent.com/101342872/157772296-01d7c7dd-2144-4207-b4d3-49e8ca3a615c.png)

But what i noticed while trying to continue playing on this version was that everytime i check on my storage, it got worse.
Got the EMC linked to my Refined Storage, with the Wireless setup (Interdimensional and Unlimited Reach upgrades), using the Universal Wireless Crafting Grid.

**Comment by ukmcplyr** [comment]
@Nemu86

Are there any/many occurances of the string "Invalid entity data item type for field" in your client's logs (both latest.log and debug.log)? I hit something that smells very similar after upgrading from 1.4 to 1.6 but haven't yet found the time to cobble together a bug report...

**Comment by Nemu86** [comment]
Tested it out again but couldn't find any of these strings in the clients logs
[debug.log](https://github.com/ChosenArchitect/Project-Architect/files/8256641/debug.log)
[latest.log](https://github.com/ChosenArchitect/Project-Architect/files/8256643/latest.log)
Attached the current log files to this post

**Comment by Coji4000** [comment]
This is happening to me (I do get the cpw error spam so maybe not identical) It started immediately after crafting the RSInfinity Items and the Universal Wireless Grid and putting them into my EMC table. I also have an Interface Linked via external storage and Advanced Export. I also use EMC links to supply items to some automations but I was able to do that without lag before the RSInfinity Items were crafted. the only new EMC links I had were some MK2s on a BiggerReactor for I/O of uranium and cyan.

Client Error Spam
`[01:38:41] [main/FATAL]: Error executing task on Client
java.lang.IllegalStateException: Invalid entity data item type for field 14 on entity WildenStalker['Wilden Stalker'/1515, l='ClientLevel', x=706.50, y=38.00, z=-44.50]: old=0(class java.lang.Integer), new={}(class net.minecraft.nbt.CompoundNBT)
	at net.minecraft.network.datasync.EntityDataManager.func_187224_a(EntityDataManager.java:245) ~[?:?]
	at net.minecraft.network.datasync.EntityDataManager.func_187218_a(EntityDataManager.java:233) ~[?:?]
	at net.minecraft.client.network.play.ClientPlayNetHandler.func_147284_a(ClientPlayNetHandler.java:552) ~[?:?]
	at net.minecraft.network.play.server.SEntityMetadataPacket.func_148833_a(SourceFile:42) ~[?:?]
	at net.minecraft.network.play.server.SEntityMetadataPacket.func_148833_a(SourceFile:11) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?]
	at net.minecraft.network.PacketThreadUtil$$Lambda$28072/1326869825.run(Unknown Source) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) [?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) [?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:948) [?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?]
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.2.31.jar:36.2]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$502/1801196366.call(Unknown Source) [forge-1.16.5-36.2.31.jar:36.2]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?]`
	
Server error Spam
`[25Mar2022 01:35:42.856] [Netty Server IO #2/ERROR] [net.minecraft.command.arguments.ArgumentTypes/]: Could not serialize cpw.mods.inventorysorter.InventorySorterCommand$ContainerClassArgument@1d99c6cd (class cpw.mods.inventorysorter.InventorySorterCommand$ContainerClassArgument) - will not be sent to client!`

**Comment by starforcraft** [comment]
Theis could be happening because of the old Universal Grid Version. Best would be to upgrade the mod lol

**Comment by Coji4000** [comment]
hoping for a v1.9.1 or something so I dont have to have all my users manually update their pack but theres no rush. I did some more poking today and can recreate the lag in a single player world with just a few items. here's the errors when its all happening locally.

`[11:04:34] [main/FATAL]: Error executing task on Client
java.lang.IndexOutOfBoundsException: Index: 46, Size: 40
	at java.util.ArrayList.rangeCheck(ArrayList.java:653) ~[?:1.8.0_51]
	at java.util.ArrayList.get(ArrayList.java:429) ~[?:1.8.0_51]
	at net.minecraft.inventory.container.Container.func_75139_a(Container.java:150) ~[?:?]
	at net.minecraft.inventory.container.Container.func_75141_a(Container.java:448) ~[?:?]
	at net.minecraft.client.network.play.ClientPlayNetHandler.func_147266_a(ClientPlayNetHandler.java:1084) ~[?:?]
	at net.minecraft.network.play.server.SSetSlotPacket.func_148833_a(SourceFile:29) ~[?:?]
	at net.minecraft.network.play.server.SSetSlotPacket.func_148833_a(SourceFile:10) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?]
	at net.minecraft.network.PacketThreadUtil$$Lambda$28048/340999344.run(Unknown Source) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) [?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) [?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:948) [?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?]
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.2.31.jar:36.2]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$502/1801196366.call(Unknown Source) [forge-1.16.5-36.2.31.jar:36.2]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?]
[11:04:34] [main/FATAL]: Error executing task on Client
java.lang.IndexOutOfBoundsException: Index: 46, Size: 40
	at java.util.ArrayList.rangeCheck(ArrayList.java:653) ~[?:1.8.0_51]
	at java.util.ArrayList.get(ArrayList.java:429) ~[?:1.8.0_51]
	at net.minecraft.inventory.container.Container.func_75139_a(Container.java:150) ~[?:?]
	at net.minecraft.inventory.container.Container.func_75141_a(Container.java:448) ~[?:?]
	at net.minecraft.client.network.play.ClientPlayNetHandler.func_147266_a(ClientPlayNetHandler.java:1084) ~[?:?]
	at net.minecraft.network.play.server.SSetSlotPacket.func_148833_a(SourceFile:29) ~[?:?]
	at net.minecraft.network.play.server.SSetSlotPacket.func_148833_a(SourceFile:10) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?]
	at net.minecraft.network.PacketThreadUtil$$Lambda$28048/340999344.run(Unknown Source) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) [?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) [?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:948) [?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?]
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.2.31.jar:36.2]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$502/1801196366.call(Unknown Source) [forge-1.16.5-36.2.31.jar:36.2]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?]
[11:05:17] [main/ERROR]: java.lang.NullPointerException
[11:05:17] [main/ERROR]: java.lang.NullPointerException
[11:05:19] [main/ERROR]: java.lang.NullPointerException
[11:05:21] [main/ERROR]: java.lang.NullPointerException
[11:05:21] [main/ERROR]: java.lang.NullPointerException
[11:05:23] [main/ERROR]: java.lang.NullPointerException`

a picture of the setup I'm using
![2022-03-25_11 09 40](https://user-images.githubusercontent.com/11728324/160147813-893059a6-e4b3-4486-9d6a-539a909fdc4f.png)

List of Items:
Crafting Grid
Controller
Disk Drive with 1x 16284 disk (prio -1)
External Storage (prio 0)
Advanced Exporter
EMC Interface
Wireless Transmitter with Infinite Range Card and Dimension Card
Universal Wireless Grid

Off Screen
Flux Controller (Wireless Charging enabled for all slots, Private Net, all else default)
Herculean Storage
Creative Power 
Energy Cell (Creative) from Powah with a flux plug stuck to it

I started a game in creative gave myself ~1 billion EMC and had my table learn up to about iron level stuff. I did this manually by wandering around but its probably easier to just spawn a bunch of random stuff to teach your EMC table. once I had a ton of emc I creatively spawned and placed the setup in the picture and the power station. immediately after linking the universal wireless grid all seems fine but about 1-2 minutes later you will begin to notice huge lags when pulling items from the grid to the point where you can watch it fill the crafting part of the grid 1 item at a time. From that point on the whole game lags and when you hold shift in your universal grid it goes blank, the lag gets extra bad when interacting with any grid from then on. Unlearning the universal grid and voiding any linked universal grids entirely seems to resolve the lag.

EDITTING TO ADD:
my workaround to prevent changing mods in the pack was to put tthe universal grid s in the jei blacklist found in path/to/modpack/config/jei/blacklist.cfg
very bottom of that file add
universalgrid:creative_wwireless_universal_grid
universalgrid:wireless_universal_grid
this will prevent it from showing up in jei and while that doesnt prevent the item from existing in game it does make it hard to craft.
